### ISSUE TITLE
Concerning the use of Skein

### ISSUE THREAD

**Issue by DonaldTsang** [tildeleb/hashland#3]
https://github.com/multiformats/go-multihash is going to use Hashland's skein hash (see https://github.com/multiformats/multicodec/blob/master/table.csv#L131)
Reference: https://github.com/multiformats/go-multihash/pull/52 and https://godoc.org/leb.io/hashland/skein

**Comment by tildeleb** [comment]
Thank  for submitting this issue. Skein was included by accident and I  have removed it.
